name: Periodic Workflow

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:    # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install FFmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py with Timeout
      run: |
        # Run main.py and wait for at most 238 minutes
        timeout 225m python bot.py
